### ISSUE TITLE
New verion 2.0.1 crashes

### ISSUE THREAD

**Issue by kubalav** [deefrawley/Flow.Launcher.Plugin.Currency#15]
I installed new version of Currency plugin and after plugin activation (via cc shortcut) plugin crashed.

```
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19041.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\WDAGUtilityAccount\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\PythonEmbeddable\pythonw.exe
Date: 04/22/2022 19:15:37
Exception:
System.IO.InvalidDataException: Currency Converter|Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Currency Converter-2.0.1\main.py", line 9, in <module>
    from plugin.currency_converter import Currency
  File "C:\Users\WDAGUtilityAccount\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Currency Converter-2.0.1\plugin\currency_converter.py", line 10, in <module>
    from flox import Flox
  File "C:\Users\WDAGUtilityAccount\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Currency Converter-2.0.1\lib\flox\__init__.py", line 57, in <module>
    APP_ICONS = os.path.join(APP_DIR, "Images")
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not tuple

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass153_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 649
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by rp1231** [comment]
I'm getting a crash in the new version as well.
Strangely the crash log shows the version to be 1.9.3 instead of 2.0.1

```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\rajpa\AppData\Roaming\FlowLauncher\Logs\1.9.3\2022-04-23.txt
2. copy below exception message

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/23/2022 00:36:57
Exception:
System.IO.InvalidDataException: Currency Converter|Exception ignored in: <function Launcher.__del__ at 0x000001F81763DC60>
Traceback (most recent call last):
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.1\lib\flox\launcher.py", line 16, in __del__
    self.run(debug)
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.1\lib\flox\launcher.py", line 47, in run
    results = self.exception(e) or self._results
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.1\lib\flox\__init__.py", line 120, in exception
    self.issue_item(exception)
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.1\lib\flox\__init__.py", line 140, in issue_item
    trace = ''.join(traceback.format_exception(etype=type(e), value=e, tb=e.__traceback__)).replace('\n', '%0A')
TypeError: format_exception() got an unexpected keyword argument 'etype'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ```

**Comment by kubalav** [comment]
> 

Flow Launcher version is 1.9.3
Currency plugin version is 2.0.1

**Comment by deefrawley** [comment]
Odd as the plugin is working for a few people that I know of. I have released a new version that changes the underlying library version to one that is more stable. Give it a bit to get pushed out and once done, perhaps uninstall and do a fresh install of the plugin and let me know if that fixes the issue

**Comment by rp1231** [comment]
Its still crashing for me:

Here's the log:
```
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/23/2022 06:56:25
Exception:
System.IO.InvalidDataException: Currency Converter|Exception ignored in: <function Launcher.__del__ at 0x0000027E78C31480>
Traceback (most recent call last):
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.2\lib\flox\launcher.py", line 58, in __del__
    self.__call__()
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.2\lib\flox\__init__.py", line 92, in __call__
    return super().__call__()
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.2\lib\flox\launcher.py", line 46, in __call__
    results = self.exception(e) or self._results
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.2\lib\flox\__init__.py", line 113, in exception
    self.issue_item(exception)
  File "C:\Users\rajpa\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.2\lib\flox\__init__.py", line 133, in issue_item
    trace = ''.join(traceback.format_exception(etype=type(e), value=e, tb=e.__traceback__)).replace('\n', '%0A')
TypeError: format_exception() got an unexpected keyword argument 'etype'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by deefrawley** [comment]
Hmmm, ok will look into it further and get back to you.

**Comment by deefrawley** [comment]
@rp1231 - are you using the embedded python in Flow or a system installed python? If system, is it v3.10?

**Comment by kubalav** [comment]
I can run version 2.0.2. If I enter command "cc 125 czk eur" I get this error:
```
07:18:25 ERROR (launcher.py): int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Downloads\FlowLauncher\app-1.9.3\UserData\Plugins\Currency Converter-2.0.2\lib\flox\launcher.py", line 43, in __call__
    results = request_method(*request_parameters) or self._results
  File "C:\Users\WDAGUtilityAccount\Downloads\FlowLauncher\app-1.9.3\UserData\Plugins\Currency Converter-2.0.2\lib\flox\__init__.py", line 118, in _query
    self.query(query)
  File "C:\Users\WDAGUtilityAccount\Downloads\FlowLauncher\app-1.9.3\UserData\Plugins\Currency Converter-2.0.2\plugin\currency_converter.py", line 118, in query
    ratesxml_returncode = self.getrates_xml(self.max_age)
  File "C:\Users\WDAGUtilityAccount\Downloads\FlowLauncher\app-1.9.3\UserData\Plugins\Currency Converter-2.0.2\plugin\currency_converter.py", line 193, in getrates_xml
    if (current - file) > datetime.timedelta(hours=int(max_age)):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by deefrawley** [comment]
Hi @kubalav - it wasn't picking up the settings. I've found the issue and will rollout a fix. You also lead me to another bug that I squashed in this release too when using the Euro has a currency :). We'll get there (it was a big update)

**Comment by deefrawley** [comment]
2.0.3 is live

**Comment by kubalav** [comment]
@deefrawley Yep, it's working now. 🙏

**Comment by rp1231** [comment]
Yep, If I remember correctly, I had tried a euro conversion when it crashed.
Now it's working fine.
