### ISSUE TITLE
flow launcher got an error

### ISSUE THREAD

**Issue by arnishbaruah** [deefrawley/Flow.Launcher.Plugin.Currency#21]
[2022-12-06.txt](https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/files/10163530/2022-12-06.txt)

Exception message
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/06/2022 12:23:22
Exception:
Currency Converter Exception: 
Websites: https://github.com/deefrawley/Flow.Launcher.Plugin.Currency
Author: deefrawley
Version: 2.0.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Currency Converter|Traceback (most recent call last):
  File "C:\Users\barua\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.4\main.py", line 9, in <module>
    from plugin.currency_converter import Currency
  File "C:\Users\barua\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.4\plugin\currency_converter.py", line 9, in <module>
    from plugin.translation import _
  File "C:\Users\barua\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.4\plugin\translation.py", line 17, in <module>
    translation = gettext.translation("messages", "plugin/translations/", languages=[LOCAL])
  File "gettext.py", line 588, in translation
FileNotFoundError: [Errno 2] No translation file found for domain: 'messages'

 ---> System.IO.InvalidDataException: Currency Converter|Traceback (most recent call last):
  File "C:\Users\barua\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.4\main.py", line 9, in <module>
    from plugin.currency_converter import Currency
  File "C:\Users\barua\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.4\plugin\currency_converter.py", line 9, in <module>
    from plugin.translation import _
  File "C:\Users\barua\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.4\plugin\translation.py", line 17, in <module>
    translation = gettext.translation("messages", "plugin/translations/", languages=[LOCAL])
  File "gettext.py", line 588, in translation
FileNotFoundError: [Errno 2] No translation file found for domain: 'messages'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Hi @arnishbaruah , could you try uninstalling and reinstalling the plugin from within Flow? The error relates to the translations but all files are in the plugin package and work elsewhere so I'm thinking there might be files missing for whatever reason

**Comment by deefrawley** [comment]
Closing as no update for a year
