### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by sonmitdev** [deefrawley/Flow.Launcher.Plugin.Currency#23]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1500, in __init__
  File "<frozen zipimport>", line 259, in load_module
  File "xml\parsers\expat.py", line 4, in <module>
ModuleNotFoundError: No module named 'pyexpat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml\etree\ElementTree.py", line 1503, in __init__
ModuleNotFoundError: No module named 'pyexpat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chenf\PA\PortableApps\FlowLauncher\app-1.10.1\UserData\Plugins\Currency Converter-2.0.3\lib\flox\launcher.py", line 43, in __call__
    results = request_method(*request_parameters) or self._results
  File "C:\Users\chenf\PA\PortableApps\FlowLauncher\app-1.10.1\UserData\Plugins\Currency Converter-2.0.3\lib\flox\__init__.py", line 118, in _query
    self.query(query)
  File "C:\Users\chenf\PA\PortableApps\FlowLauncher\app-1.10.1\UserData\Plugins\Currency Converter-2.0.3\plugin\currency_converter.py", line 120, in query
    ratedict = self.populate_rates("eurofxref-daily.xml")
  File "C:\Users\chenf\PA\PortableApps\FlowLauncher\app-1.10.1\UserData\Plugins\Currency Converter-2.0.3\plugin\currency_converter.py", line 162, in populate_rates
    tree = ET.parse(xml)
  File "xml\etree\ElementTree.py", line 1202, in parse
  File "xml\etree\ElementTree.py", line 589, in parse
  File "xml\etree\ElementTree.py", line 1505, in __init__
ImportError: No module named expat

**Comment by deefrawley** [comment]
Can you confirm you have the latest version of Flow and the plugin?

Also did you let Flow install Python or are using an existing installation, eg a 2.7 install?

**Comment by deefrawley** [comment]
Closing as no update for a year
