### ISSUE TITLE
flow launcher got an error (un- & reinstall does not work)

### ISSUE THREAD

**Issue by skakspilleren** [deefrawley/Flow.Launcher.Plugin.Currency#27]
Flow Launcher version: 1.16.2
OS Version: 22621.2715
IntPtr Length: 8
x64: True

Python Path: C:\Users\klr\AppData\Local\Programs\Python\Python311\python.exe
Node Path: 
Date: 11/17/2023 08:24:26
Exception:
Currency Converter Exception: 
Websites: https://github.com/deefrawley/Flow.Launcher.Plugin.Currency
Author: deefrawley
Version: 2.0.6
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\klr\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.6\lib\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (None)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

 ---> System.IO.InvalidDataException: C:\Users\klr\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-2.0.6\lib\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (None)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
For some reason it is using the python package urllib 2.0.7 instead of 1.26. 
Can you check the equivalent diriectory on your PC as this screenshot and see what urllib version is there

![image](https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/assets/18594055/02f22d42-ce52-4402-abd0-f62847284ff5)

**Comment by skakspilleren** [comment]
The folder (and urllib) seems to be 100% identical to yours?!
![Skærmbillede 2023-11-17 120729](https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/assets/128979459/f3e7d446-ffba-4c12-81c9-97324bea65c3)

**Comment by deefrawley** [comment]
Odd. Do you have another installation of Python on your PC?

**Comment by skakspilleren** [comment]
Yes I installed Python 3.11 from python.org. 
Mind you I've been using Macs for the last 20 years, so I'm slightly at a loss when
it comes to where stuff is on a pc :-) I suppose urllib v2 is called instead of v1.26.15 because it's
in my (python ?) path ?

**Comment by deefrawley** [comment]
Best thing to do is, even with another Python install, let Flow download the embedded Python and use that for Plugins. Python path should look like this.

![image](https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/assets/18594055/f52bf5da-791d-4515-a7bc-060445806458)

Clear this setting, Quit and restart Flow and it should ask you if you want it to download Python. Click yes.

**Comment by skakspilleren** [comment]
Problem solved, thanks!
Now FlowLauncher uses it's own python install, located here: C:\Users\user\AppData\Roaming\FlowLauncher\Environments\Python

**Comment by skakspilleren** [comment]
Problem solved, thanks!
Now FlowLauncher uses it's own python install, located here: 
C:\Users\user\AppData\Roaming\FlowLauncher\Environments\Python
