### ISSUE TITLE
Flow dev branch: .NET crash

### ISSUE THREAD

**Issue by deefrawley** [deefrawley/Flow.Launcher.Plugin.Currency#9]
For the CC plugin, I display the command syntax in the query response until the correct number of arguments are found like so

![image](https://user-images.githubusercontent.com/18594055/124057600-21e5db80-da6b-11eb-9549-e331546cfe96.png)

If you right click on this result, a .NET exception is thrown which kills Flow and I have to kill the process in Task Manager and restart.

'''Flow Launcher version: 1.7.2
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/01/2021 12:45:38
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.MainViewModel.QueryContextMenu() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 387
   at Flow.Launcher.ViewModel.MainViewModel.Query() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 368
   at Flow.Launcher.ViewModel.MainViewModel.set_QueryText(String value) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 282
   at Flow.Launcher.ViewModel.MainViewModel.set_SelectedResults(ResultsViewModel value) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 330
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_8(Object _) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 222
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 234
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)'''

This doesn't happen with other plugins, even Python ones though there query result is 'activate plugin' (I used the RollDice plugin as a comparison).

@jjw24 can you decipher the .NET exception to see what is going here?

**Comment by jjw24** [comment]
So when you right click, the code is expecting context menu, in your case it's got a null object. Do you need to initialize context menu in python plugins?

**Comment by deefrawley** [comment]
I don't have anything in my code to initialize. The RollDice plugin doesn't either, and though it works when you right click on the query result before entering arguments, if you right click after, you get the same crash.
@Zeroto521 - does the Python template need an update to initialize the context menu. If so how?

**Comment by taooceros** [comment]
I think it shall not crash the program, so we should add a check for that.

However, why should it kills Flow? Isn't we have the exception handling strategy?

**Comment by jjw24** [comment]
Not sure, I have not had a chance to look at the code yet

**Comment by jjw24** [comment]
> I don't have anything in my code to initialize. The RollDice plugin doesn't either, and though it works when you right click on the query result before entering arguments, if you right click after, you get the same crash.
> @Zeroto521 - does the Python template need an update to initialize the context menu. If so how?

I think this should be optional

**Comment by taooceros** [comment]
> I think this should be optional going forward

I agree, but we should still add that to the template or people will not know how to implement that.

**Comment by jjw24** [comment]
Agree

**Comment by taooceros** [comment]
> If you right click on this result, a .NET exception is thrown which kills Flow and I have to kill the process in Task Manager and restart.


From my testing, it won't kill Flow, but just notice that an error is thrown, which is expected.

**Comment by jjw24** [comment]
@deefrawley once the pr is successfully built, should be able to test it

**Comment by deefrawley** [comment]
> > If you right click on this result, a .NET exception is thrown which kills Flow and I have to kill the process in Task Manager and restart.
> 
> From my testing, it won't kill Flow, but just notice that an error is thrown, which is expected.

Flow remains active and can be called via the global hotkey, but no commands or plugins respond with anything. If I right click and exit from the task bar, a flow launcher exe remains in the task manager which means when I try to restart flow, nothing happens.

**Comment by taooceros** [comment]
> > > If you right click on this result, a .NET exception is thrown which kills Flow and I have to kill the process in Task Manager and restart.
> > 
> > 
> > From my testing, it won't kill Flow, but just notice that an error is thrown, which is expected.
> 
> Flow remains active and can be called via the global hotkey, but no commands or plugins respond with anything. If I right click and exit from the task bar, a flow launcher exe remains in the task manager which means when I try to restart flow, nothing happens.

That's because you have entered the context menu but nothing appears due to the exception. So an `esc` is needed to exit the context menu view. The fix should address the issue.

**Comment by deefrawley** [comment]
So do Python plugins need to do anything extra or will the fix handle things as is?

**Comment by Zeroto521** [comment]
On the Python side, there should have some specific conditions.

I don't meet using the context menu application yet.

---

The default JSON RPC returns is `[]`.

https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python/blob/1e95f0df1853bee026c3bfea64ff48ea133db884/flowlauncher/FlowLauncher.py#L35-L45

If `context_menu` has bugs, `query` would get the same.
But `query` works still well.

**Comment by taooceros** [comment]
> On the Python side, there should have some specific conditions.
> 
> I don't meet using the context menu application yet.
> 
> The default JSON RPC returns is `[]`.
> 
> https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python/blob/1e95f0df1853bee026c3bfea64ff48ea133db884/flowlauncher/FlowLauncher.py#L35-L45
> 
> If `context_menu` has bugs, `query` would get the same.
> But `query` works still well.

Let me take another round of check for it.

**Comment by taooceros** [comment]
I probably found the issue. The context menu query may not be deserialized successfully due to a legacy bug, which leads to the empty output. The fix from https://github.com/Flow-Launcher/Flow.Launcher/pull/538 should address it.

**Comment by pc223** [comment]
> So do Python plugins need to do anything extra or will the fix handle things as is?

Seems @taooceros https://github.com/Flow-Launcher/Flow.Launcher/pull/537 and https://github.com/Flow-Launcher/Flow.Launcher/pull/538 fix the issue, I tested on 2 python plugins, seems good now. 

I don't think the Python plugin side have to change anything

**Comment by jjw24** [comment]
No python side no need to address anything. We will add the initialization of context menu to the template and guide that I will eventually write up if no one has done it lol, but none you need to do extra. It's not compulsory to initialize for python plugins.

**Comment by taooceros** [comment]
So closing this one?
